CREATE TABLE PLAYERS(
    ID int,
    name varchar(30),
    position varchar(15),
    age int,
    nation varchar(30),
    club varchar(50),
    price varchar(13)
);
CREATE TABLE USERS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR2(100) NOT NULL,   
    password VARCHAR2(255) NOT NULL, 
    club VARCHAR2(100) NOT NULL,   
    role VARCHAR2(50) NOT NULL,    
    email VARCHAR2(100) UNIQUE NOT NULL, 
    phone NUMBER NOT NULL,         
    verify NUMBER(1) NOT NULL,   
    avatar VARCHAR2(255)          
);
