export interface Player {
  name: string;
  position: string;
  age: number;
  nation: string;
  club?: string;
  price: string;
}

export const initialPlayer: Player[] = [
  {
    name: "Mile Svilar",
    position: "Bramkarz",
    age: 24,
    nation: "Serbia",
    club: "AS Roma",
    price: "9,00mln €",
  },
  {
    name: "Mathew Ryan",
    position: "Bramkarz",
    age: 32,
    nation: "Australia",
    club: "AS Roma",
    price: "3,50mln €",
  },
  {
    name: "Evan Ndicka",
    position: "Środkowy Obrońca",
    age: 24,
    nation: "Wybrzeże Kości Słoniowej",
    club: "AS Roma",
    price: "25,00mln €",
  },
  {
    name: "Gianluca Mancini",
    position: "Środkowy Obrońca",
    age: 28,
    nation: "Włochy",
    club: "AS Roma",
    price: "25,00mln €",
  },
  {
    name: "Chris Smalling",
    position: "Środkowy Obrońca",
    age: 34,
    nation: "Anglia",
    club: "AS Roma",
    price: "2,50mln €",
  },
  {
    name: "Angelino",
    position: "Lewy Obrońca",
    age: 27,
    nation: "Hiszpania",
    club: "AS Roma",
    price: "8,00mln €",
  },
  {
    name: "Samuel Dahl",
    position: "Lewy Obrońca",
    age: 21,
    nation: "Szwecja",
    club: "AS Roma",
    price: "3,00mln €",
  },
  {
    name: "Zeki Celik",
    position: "Prawy Obrońca",
    age: 27,
    nation: "Turcja",
    club: "AS Roma",
    price: "6,00mln €",
  },
  {
    name: "Rick Karsdorp",
    position: "Prawy Obrońca",
    age: 29,
    nation: "Holandia",
    club: "AS Roma",
    price: "5,00mln €",
  },
  {
    name: "Bryan Cristante",
    position: "Defensywny Pomocnik",
    age: 29,
    nation: "Włochy",
    club: "AS Roma",
    price: "20,00mln €",
  },
  {
    name: "Leonardo Paredes",
    position: "Defensywny Pomocnik",
    age: 30,
    nation: "Argentyna",
    club: "AS Roma",
    price: "8,00mln €",
  },
  {
    name: "Enzo La Fee",
    position: "Środkowy Pomocnik",
    age: 24,
    nation: "Francja",
    club: "AS Roma",
    price: "18,00mln €",
  },
  {
    name: "Edoardo Bove",
    position: "Środkowy Pomocnik",
    age: 22,
    nation: "Włochy",
    club: "AS Roma",
    price: "18,00mln €",
  },
  {
    name: "Niccolo Pisilli",
    position: "Środkowy Pomocnik",
    age: 19,
    nation: "Włochy",
    club: "AS Roma",
    price: "3,50mln €",
  },
  {
    name: "Nicola Zalewski",
    position: "Lewy Pomocnik",
    age: 22,
    nation: "Polska",
    club: "AS Roma",
    price: "12,00mln €",
  },
  {
    name: "Lorenzo Pellegrini",
    position: "Ofensywny Pomocnik",
    age: 28,
    nation: "Włochy",
    club: "AS Roma",
    price: "25,00mln €",
  },
  {
    name: "Tommaso Baldanzi",
    position: "Ofensywny Pomocnik",
    age: 21,
    nation: "Włochy",
    club: "AS Roma",
    price: "15,00mln €",
  },
  {
    name: "Stephan El Shaarawy",
    position: "Lewy Napastnik",
    age: 31,
    nation: "Włochy",
    club: "AS Roma",
    price: "5,00mln €",
  },
  {
    name: "Matias Soule",
    position: "Prawy Napastnik",
    age: 21,
    nation: "Argentyna",
    club: "AS Roma",
    price: "25,00mln €",
  },
  {
    name: "Joao Costa",
    position: "Prawy Napastnik",
    age: 19,
    nation: "Brazylia",
    club: "AS Roma",
    price: "1,00mln €",
  },
  {
    name: "Paulo Dybala",
    position: "Cofnięty Napastnik",
    age: 30,
    nation: "Argentyna",
    club: "AS Roma",
    price: "20,00mln €",
  },
  {
    name: "Artem Dovbyk",
    position: "Środkowy Napastnik",
    age: 27,
    nation: "Ukraina",
    club: "AS Roma",
    price: "35,00mln €",
  },
  {
    name: "Tammy Abraham",
    position: "Środkowy Napastnik",
    age: 26,
    nation: "Anglia",
    club: "AS Roma",
    price: "30,00mln €",
  },
  {
    name: "Eldor Shomurodov",
    position: "Środkowy Napastnik",
    age: 29,
    nation: "Uzbekistan",
    club: "AS Roma",
    price: "5,00mln €",
  },
];
